### ISSUE TITLE
FATE V3 can not use

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-contracts#137]
<img width="1086" alt="image" src="https://github.com/aeternity/aepp-contracts/assets/8652427/5cb0f2d7-a706-4642-9e1f-8c3e2427b180">

**Comment by thepiwo** [comment]
will be fixed in https://github.com/unit214/aepp-contracts/commit/38920ed38fc0541f794878c6a86fda9dc3bae877 and released asap

**Comment by thepiwo** [comment]
has been fixed in https://github.com/aeternity/aepp-contracts/releases/tag/v2.3.0
