### ISSUE TITLE
Allow to select the compiler version to use to build the contract 

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-contracts#48]
you can get the list of the available compilers from compiler.aepps.com

**Comment by thepiwo** [comment]
@noandrea where can I find the source for this site?

**Comment by noandrea** [comment]
right now it is here https://github.com/noandrea/contracts-library

**Comment by maptuhec** [comment]
@noandrea @thepiwo  By *selecting the compiler version* you mean to select the compiler itself? Currently, the contracts aepp uses the hosted compiler *compiler.aepps.com*. So we want to have the ability to choose different compiler or the hosted compiler will provide multiple version and the user will be able to choose?

**Comment by thepiwo** [comment]
as compiler.aepps.com shows, it provides multiple hosted versions that could be choosen

**Comment by thepiwo** [comment]
I guess this is currently a "won't fix"
