### ISSUE TITLE
Unable to use testnet.contracts

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-contracts#52]
As of yesterday morning.

![Clipboard - October 11, 2019 6_50 AM](https://user-images.githubusercontent.com/13139371/66698410-89cc1f80-ece6-11e9-8d0e-cbe7fc125b93.png)

**Comment by maptuhec** [comment]
@mradkov  Should be fixed now with the latest release, can you please check this out. 

Thanks,
Martin

**Comment by mradkov** [comment]
It's working now. Closing.
