### ISSUE TITLE
Error: Data doesn't match expected type ak (wrong private/public key)

### ISSUE THREAD

**Issue by VitalJeevanjot** [aeternity/aepp-contracts#66]
Trying on iris branch, Updated sdk to latest version, but still getting

![image](https://user-images.githubusercontent.com/40867747/122435167-637b7e80-cfb5-11eb-9f53-e1e1cecce357.png)

**Comment by marc0olo** [comment]
@genievot maybe this is related to https://github.com/aeternity/aepp-sdk-js/issues/1224 - can you check that? probably the SDK is somewhere initialized without providing an account. should hopefully be fixed soon.

are you planning to provide a PR that makes this editor compatible with Iris and the latest compiler? I see that there is already a draft of @mradkov => https://github.com/aeternity/aepp-contracts/pull/65

**Comment by genievot** [comment]
Thanks, @marc0olo.

> are you planning to provide a PR that makes this editor compatible with Iris and the latest compiler?

Not currently, trying to use mradkov's commits.

**Comment by thepiwo** [comment]
closing as its quite an old issue, please reopen if its still a problem
