### ISSUE TITLE
ACI - show the format returned by compiler

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-contracts#78]
## Current output
```json
{
  "encodedAci": {
    "contract": {
      "functions": [
        {
          "arguments": [
            {
              "name": "x",
              "type": "int"
            }
          ],
          "name": "example",
          "payable": false,
          "returns": "int",
          "stateful": false
        }
      ],
      "kind": "contract_main",
      "name": "Example",
      "payable": false,
      "type_defs": []
    }
  },
  "externalEncodedAci": []
}
```

## Expected output
```json
{
   "encoded_aci":{
      "contract":{
         "functions":[
            {
               "arguments":[
                  {
                     "name":"x",
                     "type":"int"
                  }
               ],
               "name":"example",
               "payable":false,
               "returns":"int",
               "stateful":false
            }
         ],
         "kind":"contract_main",
         "name":"Example",
         "payable":false,
         "type_defs":[
            
         ]
      }
   },
   "external_encoded_aci":[
      
   ],
   "interface":"main contract Example =\n  entrypoint example : (int) => int\n"
}
```

as far as I remember we agreed that we want to use the ACI version returned by the http compiler instead of using the version translated by the SDK. cc @hanssv @kenodressel @thepiwo @kalovelo @nikita-fuchs @radrow 

also I am not sure about the reason to drop the `interface`. this was mainly requested by @thepiwo. I didn't remove it now in the example here. just wanted to make sure we agree on dropping it. in the SDK we could just ignore the `interface` if not needed (cc @davidyuk)

**Comment by thepiwo** [comment]
We discussed to expose without interface and in the format the sdk requires right?

**Comment by marc0olo** [comment]
> We discussed to expose without interface and in the format the sdk requires right?

this is exactly what I am questioning. from my understanding we agreed to stick to the format returned by the http compiler (which is NOT camelCase)

if we prefer the camelCase format like it's currently done in the SDK we should adapt the http compiler IMO (cc @hanssv @radrow @ghallak @davidyuk)

I have no strong opinion, but we should be aligned on that. I am also not sure about the reasoning we "manipulate" that right now in the SDK

**Comment by marc0olo** [comment]
ok, so let's put this one on hold until we have the changes in the SDK like discussed. then we should probably see the "correct" format of the ACI here if the SDK is updated, right? :)
