### ISSUE TITLE
cannot provide deployment arguments for `init`

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-contracts#95]
reported by hackathon participant on Discord who used this example

```
@compiler >= 4

contract Example =
  record state = {
    x: int
   }
  entrypoint init(x: int) =
    {
      x = x
     }
  entrypoint example(x : int) = x
```

![image](https://user-images.githubusercontent.com/8124114/235963066-b0297833-3c2c-4251-b92b-acc1c64ef766.png)

**Comment by thepiwo** [comment]
fix deployed
